services:
  - type: web
    name: happy_protein
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn happy_protein.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4